Traceback (most recent call last):
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/open-machine-learning-jupyter-book/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fruits.remove('grape')
assert fruits == ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

with pytest.raises(Exception):
    fruits.remove('not existing element')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn [65], line 1[0m
[0;32m----> 1[0m fruits[38;5;241m.[39mremove([38;5;124m'[39m[38;5;124mgrape[39m[38;5;124m'[39m)
[1;32m      2[0m [38;5;28;01massert[39;00m fruits [38;5;241m==[39m [[38;5;124m'[39m[38;5;124morange[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mapple[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mpear[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mbanana[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mkiwi[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mapple[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mbanana[39m[38;5;124m'[39m]
[1;32m      4[0m [38;5;28;01mwith[39;00m pytest[38;5;241m.[39mraises([38;5;167;01mException[39;00m):

[0;31mValueError[0m: list.remove(x): x not in list
ValueError: list.remove(x): x not in list

